package com.mycma.core.domain;

import java.time.Instant;
import java.util.Objects;

/**
 * Represents a piece of content generated by AI (copy or image).
 * Pure domain entity — no framework annotations.
 */
public class AiGeneration {

    public enum Type {
        COPY,
        IMAGE
    }

    private final String id;
    private final Type type;
    private final String originalPrompt;
    private final String generatedText;       // for COPY type
    private final String generatedImagePath;  // for IMAGE type (local file path)
    private final String modelUsed;
    private final int tokensUsed;
    private final Instant createdAt;

    public AiGeneration(String id, Type type, String originalPrompt,
                        String generatedText, String generatedImagePath,
                        String modelUsed, int tokensUsed, Instant createdAt) {
        this.id = Objects.requireNonNull(id);
        this.type = Objects.requireNonNull(type);
        this.originalPrompt = Objects.requireNonNull(originalPrompt);
        this.generatedText = generatedText;
        this.generatedImagePath = generatedImagePath;
        this.modelUsed = modelUsed;
        this.tokensUsed = tokensUsed;
        this.createdAt = Objects.requireNonNull(createdAt);
    }

    public String getId() { return id; }
    public Type getType() { return type; }
    public String getOriginalPrompt() { return originalPrompt; }
    public String getGeneratedText() { return generatedText; }
    public String getGeneratedImagePath() { return generatedImagePath; }
    public String getModelUsed() { return modelUsed; }
    public int getTokensUsed() { return tokensUsed; }
    public Instant getCreatedAt() { return createdAt; }
}
